# generate a trigger to run the unit tests on every push to any branch

name: Unit Test

on:
  push:
    branches:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # for current project on typescript
      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
